# Generated by Django 3.0.2 on 2020-02-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=30)),
                ('ccolor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Car',
            },
        ),
    ]
